//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsageReporting
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthenticationInfo", Namespace="http://schemas.datacontract.org/2004/07/Panopto.Server.Services.PublicAPI.V40")]
    public partial class AuthenticationInfo : object
    {
        
        private string AuthCodeField;
        
        private string PasswordField;
        
        private string UserKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuthCode
        {
            get
            {
                return this.AuthCodeField;
            }
            set
            {
                this.AuthCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserKey
        {
            get
            {
                return this.UserKeyField;
            }
            set
            {
                this.UserKeyField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsageGranularity", Namespace="http://schemas.datacontract.org/2004/07/Panopto.Server.Services.PublicAPI.V40")]
    public enum UsageGranularity : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Hourly = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Daily = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Weekly = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SummaryUsageResponseItem", Namespace="http://schemas.datacontract.org/2004/07/Panopto.Server.Services.PublicAPI.V40")]
    public partial class SummaryUsageResponseItem : object
    {
        
        private double MinutesViewedField;
        
        private System.DateTime TimeField;
        
        private int UniqueUsersField;
        
        private int ViewsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double MinutesViewed
        {
            get
            {
                return this.MinutesViewedField;
            }
            set
            {
                this.MinutesViewedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Time
        {
            get
            {
                return this.TimeField;
            }
            set
            {
                this.TimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UniqueUsers
        {
            get
            {
                return this.UniqueUsersField;
            }
            set
            {
                this.UniqueUsersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Views
        {
            get
            {
                return this.ViewsField;
            }
            set
            {
                this.ViewsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pagination", Namespace="http://schemas.datacontract.org/2004/07/Panopto.Server.Services.PublicAPI.V40")]
    public partial class Pagination : object
    {
        
        private int MaxNumberResultsField;
        
        private int PageNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxNumberResults
        {
            get
            {
                return this.MaxNumberResultsField;
            }
            set
            {
                this.MaxNumberResultsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageNumber
        {
            get
            {
                return this.PageNumberField;
            }
            set
            {
                this.PageNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetailedUsageResponse", Namespace="http://schemas.datacontract.org/2004/07/Panopto.Server.Services.PublicAPI.V40")]
    public partial class DetailedUsageResponse : object
    {
        
        private UsageReporting.DetailedUsageResponseItem[] PagedResponsesField;
        
        private int TotalNumberResponsesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UsageReporting.DetailedUsageResponseItem[] PagedResponses
        {
            get
            {
                return this.PagedResponsesField;
            }
            set
            {
                this.PagedResponsesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalNumberResponses
        {
            get
            {
                return this.TotalNumberResponsesField;
            }
            set
            {
                this.TotalNumberResponsesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetailedUsageResponseItem", Namespace="http://schemas.datacontract.org/2004/07/Panopto.Server.Services.PublicAPI.V40")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UsageReporting.ExtendedDetailedUsageResponseItem))]
    public partial class DetailedUsageResponseItem : object
    {
        
        private double SecondsViewedField;
        
        private System.Guid SessionIdField;
        
        private double StartPositionField;
        
        private System.DateTime TimeField;
        
        private System.Guid UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double SecondsViewed
        {
            get
            {
                return this.SecondsViewedField;
            }
            set
            {
                this.SecondsViewedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid SessionId
        {
            get
            {
                return this.SessionIdField;
            }
            set
            {
                this.SessionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double StartPosition
        {
            get
            {
                return this.StartPositionField;
            }
            set
            {
                this.StartPositionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Time
        {
            get
            {
                return this.TimeField;
            }
            set
            {
                this.TimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExtendedDetailedUsageResponseItem", Namespace="http://schemas.datacontract.org/2004/07/Panopto.Server.Services.PublicAPI.V40")]
    public partial class ExtendedDetailedUsageResponseItem : UsageReporting.DetailedUsageResponseItem
    {
        
        private System.Nullable<double> PlaybackSpeedField;
        
        private UsageReporting.ExtendedDetailedUsageResponseItem.StartReasons StartReasonField;
        
        private UsageReporting.ExtendedDetailedUsageResponseItem.StopReasons StopReasonField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> PlaybackSpeed
        {
            get
            {
                return this.PlaybackSpeedField;
            }
            set
            {
                this.PlaybackSpeedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UsageReporting.ExtendedDetailedUsageResponseItem.StartReasons StartReason
        {
            get
            {
                return this.StartReasonField;
            }
            set
            {
                this.StartReasonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UsageReporting.ExtendedDetailedUsageResponseItem.StopReasons StopReason
        {
            get
            {
                return this.StopReasonField;
            }
            set
            {
                this.StopReasonField = value;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="ExtendedDetailedUsageResponseItem.StartReasons", Namespace="http://schemas.datacontract.org/2004/07/Panopto.Server.Services.PublicAPI.V40")]
        public enum StartReasons : int
        {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Start = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Seek = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Resume = 2,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            NewSpeed = 3,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Unknown = 4,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Unexpected = 5,
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="ExtendedDetailedUsageResponseItem.StopReasons", Namespace="http://schemas.datacontract.org/2004/07/Panopto.Server.Services.PublicAPI.V40")]
        public enum StopReasons : int
        {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            End = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Seek = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Pause = 2,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            SpeedChange = 3,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            PlayerClose = 4,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Unknown = 5,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Unexpected = 6,
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExtendedDetailedUsageResponse", Namespace="http://schemas.datacontract.org/2004/07/Panopto.Server.Services.PublicAPI.V40")]
    public partial class ExtendedDetailedUsageResponse : object
    {
        
        private UsageReporting.ExtendedDetailedUsageResponseItem[] PagedResponsesField;
        
        private int TotalNumberResponsesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UsageReporting.ExtendedDetailedUsageResponseItem[] PagedResponses
        {
            get
            {
                return this.PagedResponsesField;
            }
            set
            {
                this.PagedResponsesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalNumberResponses
        {
            get
            {
                return this.TotalNumberResponsesField;
            }
            set
            {
                this.TotalNumberResponsesField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatsReportType", Namespace="http://schemas.datacontract.org/2004/07/Panopto.Server.Services.PublicAPI.V40")]
    public enum StatsReportType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FolderUsage = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SessionUsage = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserViewingUsage = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserCreationUsage = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LastLoginTime = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SessionsViewsByUsers = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SessionsViewsByViewingType = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SessionsCreatedOrEdited = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RemoteRecorderUsage = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SystemViews = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SystemFolderStorage = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        StreamCreation = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RetentionAudit = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SystemSessionStorage = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RetentionAuditImpact = 14,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatsReportStatus", Namespace="http://schemas.datacontract.org/2004/07/Panopto.Server.Services.PublicAPI.V40")]
    public partial class StatsReportStatus : object
    {
        
        private System.DateTime EndTimeField;
        
        private bool IsAvailableField;
        
        private System.Guid ReportIdField;
        
        private System.Nullable<System.DateTime> ReportTimeField;
        
        private UsageReporting.StatsReportType ReportTypeField;
        
        private System.DateTime StartTimeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndTime
        {
            get
            {
                return this.EndTimeField;
            }
            set
            {
                this.EndTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAvailable
        {
            get
            {
                return this.IsAvailableField;
            }
            set
            {
                this.IsAvailableField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ReportId
        {
            get
            {
                return this.ReportIdField;
            }
            set
            {
                this.ReportIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ReportTime
        {
            get
            {
                return this.ReportTimeField;
            }
            set
            {
                this.ReportTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UsageReporting.StatsReportType ReportType
        {
            get
            {
                return this.ReportTypeField;
            }
            set
            {
                this.ReportTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartTime
        {
            get
            {
                return this.StartTimeField;
            }
            set
            {
                this.StartTimeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecurringReportCadence", Namespace="http://schemas.datacontract.org/2004/07/Panopto.Server.Services.PublicAPI.V40")]
    public enum RecurringReportCadence : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Daily = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Weekly = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Monthly = 30,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecurringStatsReportDefinition", Namespace="http://schemas.datacontract.org/2004/07/Panopto.Server.Services.PublicAPI.V40")]
    public partial class RecurringStatsReportDefinition : object
    {
        
        private UsageReporting.RecurringReportCadence CadenceField;
        
        private System.Guid DefinitionIdField;
        
        private bool IsEnabledField;
        
        private int OffsetField;
        
        private UsageReporting.StatsReportType ReportTypeField;
        
        private UsageReporting.StatsReportStatus[] ReportsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UsageReporting.RecurringReportCadence Cadence
        {
            get
            {
                return this.CadenceField;
            }
            set
            {
                this.CadenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid DefinitionId
        {
            get
            {
                return this.DefinitionIdField;
            }
            set
            {
                this.DefinitionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsEnabled
        {
            get
            {
                return this.IsEnabledField;
            }
            set
            {
                this.IsEnabledField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Offset
        {
            get
            {
                return this.OffsetField;
            }
            set
            {
                this.OffsetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UsageReporting.StatsReportType ReportType
        {
            get
            {
                return this.ReportTypeField;
            }
            set
            {
                this.ReportTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UsageReporting.StatsReportStatus[] Reports
        {
            get
            {
                return this.ReportsField;
            }
            set
            {
                this.ReportsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QuizResultReportType", Namespace="http://schemas.datacontract.org/2004/07/Panopto.Server.Services.PublicAPI.V40")]
    public enum QuizResultReportType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserResultsSummary = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DetailedResultsBySection = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UsageReporting.IUsageReporting")]
    public interface IUsageReporting
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsageReporting/GetSystemSummaryUsage", ReplyAction="http://tempuri.org/IUsageReporting/GetSystemSummaryUsageResponse")]
        UsageReporting.SummaryUsageResponseItem[] GetSystemSummaryUsage(UsageReporting.AuthenticationInfo auth, System.DateTime beginRange, System.DateTime endRange, UsageReporting.UsageGranularity granularity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsageReporting/GetFolderSummaryUsage", ReplyAction="http://tempuri.org/IUsageReporting/GetFolderSummaryUsageResponse")]
        UsageReporting.SummaryUsageResponseItem[] GetFolderSummaryUsage(UsageReporting.AuthenticationInfo auth, System.Guid folderId, System.DateTime beginRange, System.DateTime endRange, UsageReporting.UsageGranularity granularity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsageReporting/GetSessionSummaryUsage", ReplyAction="http://tempuri.org/IUsageReporting/GetSessionSummaryUsageResponse")]
        UsageReporting.SummaryUsageResponseItem[] GetSessionSummaryUsage(UsageReporting.AuthenticationInfo auth, System.Guid sessionId, System.DateTime beginRange, System.DateTime endRange, UsageReporting.UsageGranularity granularity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsageReporting/GetSessionDetailedUsage", ReplyAction="http://tempuri.org/IUsageReporting/GetSessionDetailedUsageResponse")]
        UsageReporting.DetailedUsageResponse GetSessionDetailedUsage(UsageReporting.AuthenticationInfo auth, System.Guid sessionId, UsageReporting.Pagination pagination, System.DateTime beginRange, System.DateTime endRange);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsageReporting/GetSessionExtendedDetailedUsage", ReplyAction="http://tempuri.org/IUsageReporting/GetSessionExtendedDetailedUsageResponse")]
        UsageReporting.ExtendedDetailedUsageResponse GetSessionExtendedDetailedUsage(UsageReporting.AuthenticationInfo auth, System.Guid sessionId, UsageReporting.Pagination pagination, System.DateTime beginRange, System.DateTime endRange);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsageReporting/GetUserDetailedUsage", ReplyAction="http://tempuri.org/IUsageReporting/GetUserDetailedUsageResponse")]
        UsageReporting.DetailedUsageResponse GetUserDetailedUsage(UsageReporting.AuthenticationInfo auth, System.Guid userId, UsageReporting.Pagination pagination);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsageReporting/GetUserExtendedDetailedUsage", ReplyAction="http://tempuri.org/IUsageReporting/GetUserExtendedDetailedUsageResponse")]
        UsageReporting.ExtendedDetailedUsageResponse GetUserExtendedDetailedUsage(UsageReporting.AuthenticationInfo auth, System.Guid userId, UsageReporting.Pagination pagination, System.DateTime beginRange, System.DateTime endRange);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsageReporting/GetSessionUserDetailedUsage", ReplyAction="http://tempuri.org/IUsageReporting/GetSessionUserDetailedUsageResponse")]
        UsageReporting.DetailedUsageResponse GetSessionUserDetailedUsage(UsageReporting.AuthenticationInfo auth, System.Guid sessionId, System.Guid userId, UsageReporting.Pagination pagination);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsageReporting/GetSessionUserExtendedDetailedUsage", ReplyAction="http://tempuri.org/IUsageReporting/GetSessionUserExtendedDetailedUsageResponse")]
        UsageReporting.ExtendedDetailedUsageResponse GetSessionUserExtendedDetailedUsage(UsageReporting.AuthenticationInfo auth, System.Guid sessionId, System.Guid userId, UsageReporting.Pagination pagination);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsageReporting/DescribeReportTypes", ReplyAction="http://tempuri.org/IUsageReporting/DescribeReportTypesResponse")]
        UsageReporting.StatsReportType[] DescribeReportTypes(UsageReporting.AuthenticationInfo auth);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsageReporting/DescribeReportType", ReplyAction="http://tempuri.org/IUsageReporting/DescribeReportTypeResponse")]
        string[] DescribeReportType(UsageReporting.AuthenticationInfo auth, UsageReporting.StatsReportType reportType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsageReporting/GetRecentReports", ReplyAction="http://tempuri.org/IUsageReporting/GetRecentReportsResponse")]
        UsageReporting.StatsReportStatus[] GetRecentReports(UsageReporting.AuthenticationInfo auth, System.Nullable<UsageReporting.StatsReportType> reportType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsageReporting/QueueReport", ReplyAction="http://tempuri.org/IUsageReporting/QueueReportResponse")]
        System.Guid QueueReport(UsageReporting.AuthenticationInfo auth, UsageReporting.StatsReportType reportType, System.DateTime startTime, System.DateTime endTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsageReporting/GetReport", ReplyAction="http://tempuri.org/IUsageReporting/GetReportResponse")]
        void GetReport(UsageReporting.AuthenticationInfo auth, System.Guid reportId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsageReporting/CancelReport", ReplyAction="http://tempuri.org/IUsageReporting/CancelReportResponse")]
        void CancelReport(UsageReporting.AuthenticationInfo auth, System.Guid reportId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsageReporting/CreateRecurringReport", ReplyAction="http://tempuri.org/IUsageReporting/CreateRecurringReportResponse")]
        System.Guid CreateRecurringReport(UsageReporting.AuthenticationInfo auth, UsageReporting.RecurringReportCadence cadenceType, int cadenceOffset, UsageReporting.StatsReportType reportType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsageReporting/DeleteRecurringReport", ReplyAction="http://tempuri.org/IUsageReporting/DeleteRecurringReportResponse")]
        void DeleteRecurringReport(UsageReporting.AuthenticationInfo auth, System.Guid reportId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsageReporting/GetRecurringReports", ReplyAction="http://tempuri.org/IUsageReporting/GetRecurringReportsResponse")]
        UsageReporting.RecurringStatsReportDefinition[] GetRecurringReports(UsageReporting.AuthenticationInfo auth, System.Nullable<UsageReporting.StatsReportType> reportType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsageReporting/GetQuizResultDownloadUrl", ReplyAction="http://tempuri.org/IUsageReporting/GetQuizResultDownloadUrlResponse")]
        string GetQuizResultDownloadUrl(UsageReporting.AuthenticationInfo auth, System.Guid sessionId, UsageReporting.QuizResultReportType quizResultReportType);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IUsageReportingChannel : UsageReporting.IUsageReporting, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class UsageReportingClient : System.ServiceModel.ClientBase<UsageReporting.IUsageReporting>, UsageReporting.IUsageReporting
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public UsageReportingClient(EndpointConfiguration endpointConfiguration) : 
                base(UsageReportingClient.GetBindingForEndpoint(endpointConfiguration), UsageReportingClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UsageReportingClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(UsageReportingClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UsageReportingClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(UsageReportingClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UsageReportingClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public UsageReporting.SummaryUsageResponseItem[] GetSystemSummaryUsage(UsageReporting.AuthenticationInfo auth, System.DateTime beginRange, System.DateTime endRange, UsageReporting.UsageGranularity granularity)
        {
            return base.Channel.GetSystemSummaryUsage(auth, beginRange, endRange, granularity);
        }
        
        public UsageReporting.SummaryUsageResponseItem[] GetFolderSummaryUsage(UsageReporting.AuthenticationInfo auth, System.Guid folderId, System.DateTime beginRange, System.DateTime endRange, UsageReporting.UsageGranularity granularity)
        {
            return base.Channel.GetFolderSummaryUsage(auth, folderId, beginRange, endRange, granularity);
        }
        
        public UsageReporting.SummaryUsageResponseItem[] GetSessionSummaryUsage(UsageReporting.AuthenticationInfo auth, System.Guid sessionId, System.DateTime beginRange, System.DateTime endRange, UsageReporting.UsageGranularity granularity)
        {
            return base.Channel.GetSessionSummaryUsage(auth, sessionId, beginRange, endRange, granularity);
        }
        
        public UsageReporting.DetailedUsageResponse GetSessionDetailedUsage(UsageReporting.AuthenticationInfo auth, System.Guid sessionId, UsageReporting.Pagination pagination, System.DateTime beginRange, System.DateTime endRange)
        {
            return base.Channel.GetSessionDetailedUsage(auth, sessionId, pagination, beginRange, endRange);
        }
        
        public UsageReporting.ExtendedDetailedUsageResponse GetSessionExtendedDetailedUsage(UsageReporting.AuthenticationInfo auth, System.Guid sessionId, UsageReporting.Pagination pagination, System.DateTime beginRange, System.DateTime endRange)
        {
            return base.Channel.GetSessionExtendedDetailedUsage(auth, sessionId, pagination, beginRange, endRange);
        }
        
        public UsageReporting.DetailedUsageResponse GetUserDetailedUsage(UsageReporting.AuthenticationInfo auth, System.Guid userId, UsageReporting.Pagination pagination)
        {
            return base.Channel.GetUserDetailedUsage(auth, userId, pagination);
        }
        
        public UsageReporting.ExtendedDetailedUsageResponse GetUserExtendedDetailedUsage(UsageReporting.AuthenticationInfo auth, System.Guid userId, UsageReporting.Pagination pagination, System.DateTime beginRange, System.DateTime endRange)
        {
            return base.Channel.GetUserExtendedDetailedUsage(auth, userId, pagination, beginRange, endRange);
        }
        
        public UsageReporting.DetailedUsageResponse GetSessionUserDetailedUsage(UsageReporting.AuthenticationInfo auth, System.Guid sessionId, System.Guid userId, UsageReporting.Pagination pagination)
        {
            return base.Channel.GetSessionUserDetailedUsage(auth, sessionId, userId, pagination);
        }
        
        public UsageReporting.ExtendedDetailedUsageResponse GetSessionUserExtendedDetailedUsage(UsageReporting.AuthenticationInfo auth, System.Guid sessionId, System.Guid userId, UsageReporting.Pagination pagination)
        {
            return base.Channel.GetSessionUserExtendedDetailedUsage(auth, sessionId, userId, pagination);
        }
        
        public UsageReporting.StatsReportType[] DescribeReportTypes(UsageReporting.AuthenticationInfo auth)
        {
            return base.Channel.DescribeReportTypes(auth);
        }
        
        public string[] DescribeReportType(UsageReporting.AuthenticationInfo auth, UsageReporting.StatsReportType reportType)
        {
            return base.Channel.DescribeReportType(auth, reportType);
        }
        
        public UsageReporting.StatsReportStatus[] GetRecentReports(UsageReporting.AuthenticationInfo auth, System.Nullable<UsageReporting.StatsReportType> reportType)
        {
            return base.Channel.GetRecentReports(auth, reportType);
        }
        
        public System.Guid QueueReport(UsageReporting.AuthenticationInfo auth, UsageReporting.StatsReportType reportType, System.DateTime startTime, System.DateTime endTime)
        {
            return base.Channel.QueueReport(auth, reportType, startTime, endTime);
        }
        
        public void GetReport(UsageReporting.AuthenticationInfo auth, System.Guid reportId)
        {
            base.Channel.GetReport(auth, reportId);
        }
        
        public void CancelReport(UsageReporting.AuthenticationInfo auth, System.Guid reportId)
        {
            base.Channel.CancelReport(auth, reportId);
        }
        
        public System.Guid CreateRecurringReport(UsageReporting.AuthenticationInfo auth, UsageReporting.RecurringReportCadence cadenceType, int cadenceOffset, UsageReporting.StatsReportType reportType)
        {
            return base.Channel.CreateRecurringReport(auth, cadenceType, cadenceOffset, reportType);
        }
        
        public void DeleteRecurringReport(UsageReporting.AuthenticationInfo auth, System.Guid reportId)
        {
            base.Channel.DeleteRecurringReport(auth, reportId);
        }
        
        public UsageReporting.RecurringStatsReportDefinition[] GetRecurringReports(UsageReporting.AuthenticationInfo auth, System.Nullable<UsageReporting.StatsReportType> reportType)
        {
            return base.Channel.GetRecurringReports(auth, reportType);
        }
        
        public string GetQuizResultDownloadUrl(UsageReporting.AuthenticationInfo auth, System.Guid sessionId, UsageReporting.QuizResultReportType quizResultReportType)
        {
            return base.Channel.GetQuizResultDownloadUrl(auth, sessionId, quizResultReportType);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IUsageReporting))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IUsageReporting1))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IUsageReporting))
            {
                return new System.ServiceModel.EndpointAddress("https://leedstest.cloud.panopto.eu/Panopto/PublicAPI/4.2/UsageReporting.svc");
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IUsageReporting1))
            {
                return new System.ServiceModel.EndpointAddress("http://leedstest.cloud.panopto.eu/Panopto/PublicAPI/4.2/UsageReporting.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IUsageReporting,
            
            BasicHttpBinding_IUsageReporting1,
        }
    }
}
