//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserManagement
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthenticationInfo", Namespace="http://schemas.datacontract.org/2004/07/Panopto.Server.Services.PublicAPI.V40")]
    public partial class AuthenticationInfo : object
    {
        
        private string AuthCodeField;
        
        private string PasswordField;
        
        private string UserKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuthCode
        {
            get
            {
                return this.AuthCodeField;
            }
            set
            {
                this.AuthCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserKey
        {
            get
            {
                return this.UserKeyField;
            }
            set
            {
                this.UserKeyField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/Panopto.Server.Services.PublicAPI.V40")]
    public partial class User : object
    {
        
        private string EmailField;
        
        private bool EmailSessionNotificationsField;
        
        private string FirstNameField;
        
        private System.Guid[] GroupMembershipsField;
        
        private string LastNameField;
        
        private UserManagement.SystemRole SystemRoleField;
        
        private string UserBioField;
        
        private System.Guid UserIdField;
        
        private string UserKeyField;
        
        private string UserSettingsUrlField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EmailSessionNotifications
        {
            get
            {
                return this.EmailSessionNotificationsField;
            }
            set
            {
                this.EmailSessionNotificationsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid[] GroupMemberships
        {
            get
            {
                return this.GroupMembershipsField;
            }
            set
            {
                this.GroupMembershipsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserManagement.SystemRole SystemRole
        {
            get
            {
                return this.SystemRoleField;
            }
            set
            {
                this.SystemRoleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserBio
        {
            get
            {
                return this.UserBioField;
            }
            set
            {
                this.UserBioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserKey
        {
            get
            {
                return this.UserKeyField;
            }
            set
            {
                this.UserKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserSettingsUrl
        {
            get
            {
                return this.UserSettingsUrlField;
            }
            set
            {
                this.UserSettingsUrlField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SystemRole", Namespace="http://schemas.datacontract.org/2004/07/Panopto.Server.Services.PublicAPI.V40")]
    public enum SystemRole : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Videographer = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Admin = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListUsersRequest", Namespace="http://schemas.datacontract.org/2004/07/Panopto.Server.Services.PublicAPI.V40")]
    public partial class ListUsersRequest : object
    {
        
        private UserManagement.Pagination PaginationField;
        
        private UserManagement.UserSortField SortByField;
        
        private bool SortIncreasingField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserManagement.Pagination Pagination
        {
            get
            {
                return this.PaginationField;
            }
            set
            {
                this.PaginationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserManagement.UserSortField SortBy
        {
            get
            {
                return this.SortByField;
            }
            set
            {
                this.SortByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SortIncreasing
        {
            get
            {
                return this.SortIncreasingField;
            }
            set
            {
                this.SortIncreasingField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pagination", Namespace="http://schemas.datacontract.org/2004/07/Panopto.Server.Services.PublicAPI.V40")]
    public partial class Pagination : object
    {
        
        private int MaxNumberResultsField;
        
        private int PageNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxNumberResults
        {
            get
            {
                return this.MaxNumberResultsField;
            }
            set
            {
                this.MaxNumberResultsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageNumber
        {
            get
            {
                return this.PageNumberField;
            }
            set
            {
                this.PageNumberField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserSortField", Namespace="http://schemas.datacontract.org/2004/07/Panopto.Server.Services.PublicAPI.V40")]
    public enum UserSortField : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserKey = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Role = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Added = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LastLogOn = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Email = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FullName = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListUsersResponse", Namespace="http://schemas.datacontract.org/2004/07/Panopto.Server.Services.PublicAPI.V40")]
    public partial class ListUsersResponse : object
    {
        
        private UserManagement.User[] PagedResultsField;
        
        private int TotalResultCountField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserManagement.User[] PagedResults
        {
            get
            {
                return this.PagedResultsField;
            }
            set
            {
                this.PagedResultsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalResultCount
        {
            get
            {
                return this.TotalResultCountField;
            }
            set
            {
                this.TotalResultCountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Group", Namespace="http://schemas.datacontract.org/2004/07/Panopto.Server.Services.PublicAPI.V40")]
    public partial class Group : object
    {
        
        private string ExternalIdField;
        
        private UserManagement.GroupType GroupTypeField;
        
        private System.Guid IdField;
        
        private string MembershipProviderNameField;
        
        private string NameField;
        
        private UserManagement.SystemRole SystemRoleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExternalId
        {
            get
            {
                return this.ExternalIdField;
            }
            set
            {
                this.ExternalIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserManagement.GroupType GroupType
        {
            get
            {
                return this.GroupTypeField;
            }
            set
            {
                this.GroupTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MembershipProviderName
        {
            get
            {
                return this.MembershipProviderNameField;
            }
            set
            {
                this.MembershipProviderNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserManagement.SystemRole SystemRole
        {
            get
            {
                return this.SystemRoleField;
            }
            set
            {
                this.SystemRoleField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GroupType", Namespace="http://schemas.datacontract.org/2004/07/Panopto.Server.Services.PublicAPI.V40")]
    public enum GroupType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ActiveDirectory = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        External = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Internal = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListGroupsResponse", Namespace="http://schemas.datacontract.org/2004/07/Panopto.Server.Services.PublicAPI.V40")]
    public partial class ListGroupsResponse : object
    {
        
        private UserManagement.Group[] PagedResultsField;
        
        private int TotalResultCountField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserManagement.Group[] PagedResults
        {
            get
            {
                return this.PagedResultsField;
            }
            set
            {
                this.PagedResultsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalResultCount
        {
            get
            {
                return this.TotalResultCountField;
            }
            set
            {
                this.TotalResultCountField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserManagement.IUserManagement")]
    public interface IUserManagement
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/CreateUser", ReplyAction="http://tempuri.org/IUserManagement/CreateUserResponse")]
        System.Guid CreateUser(UserManagement.AuthenticationInfo auth, UserManagement.User user, string initialPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/CreateUsers", ReplyAction="http://tempuri.org/IUserManagement/CreateUsersResponse")]
        UserManagement.User[] CreateUsers(UserManagement.AuthenticationInfo auth, UserManagement.User[] users);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/GetUserByKey", ReplyAction="http://tempuri.org/IUserManagement/GetUserByKeyResponse")]
        UserManagement.User GetUserByKey(UserManagement.AuthenticationInfo auth, string userKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/GetUsers", ReplyAction="http://tempuri.org/IUserManagement/GetUsersResponse")]
        UserManagement.User[] GetUsers(UserManagement.AuthenticationInfo auth, System.Guid[] userIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/ListUsers", ReplyAction="http://tempuri.org/IUserManagement/ListUsersResponse")]
        UserManagement.ListUsersResponse ListUsers(UserManagement.AuthenticationInfo auth, UserManagement.ListUsersRequest parameters, string searchQuery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/UpdateContactInfo", ReplyAction="http://tempuri.org/IUserManagement/UpdateContactInfoResponse")]
        void UpdateContactInfo(UserManagement.AuthenticationInfo auth, System.Guid userId, string firstName, string lastName, string email, bool sendNotifications);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/UpdateUserBio", ReplyAction="http://tempuri.org/IUserManagement/UpdateUserBioResponse")]
        void UpdateUserBio(UserManagement.AuthenticationInfo auth, System.Guid userId, string bio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/UpdatePassword", ReplyAction="http://tempuri.org/IUserManagement/UpdatePasswordResponse")]
        void UpdatePassword(UserManagement.AuthenticationInfo auth, System.Guid userId, string newPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/ResetPassword", ReplyAction="http://tempuri.org/IUserManagement/ResetPasswordResponse")]
        void ResetPassword(UserManagement.AuthenticationInfo auth, System.Guid userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/UnlockAccount", ReplyAction="http://tempuri.org/IUserManagement/UnlockAccountResponse")]
        void UnlockAccount(UserManagement.AuthenticationInfo auth, System.Guid userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/SetSystemRole", ReplyAction="http://tempuri.org/IUserManagement/SetSystemRoleResponse")]
        void SetSystemRole(UserManagement.AuthenticationInfo auth, System.Guid userId, UserManagement.SystemRole role);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/DeleteUsers", ReplyAction="http://tempuri.org/IUserManagement/DeleteUsersResponse")]
        void DeleteUsers(UserManagement.AuthenticationInfo auth, System.Guid[] userIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/CreateInternalGroup", ReplyAction="http://tempuri.org/IUserManagement/CreateInternalGroupResponse")]
        UserManagement.Group CreateInternalGroup(UserManagement.AuthenticationInfo auth, string groupName, System.Guid[] memberIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/GetGroupIsPublic", ReplyAction="http://tempuri.org/IUserManagement/GetGroupIsPublicResponse")]
        bool GetGroupIsPublic(UserManagement.AuthenticationInfo auth, System.Guid groupId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/SetGroupIsPublic", ReplyAction="http://tempuri.org/IUserManagement/SetGroupIsPublicResponse")]
        void SetGroupIsPublic(UserManagement.AuthenticationInfo auth, System.Guid groupId, bool isPublic);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/CreateExternalGroup", ReplyAction="http://tempuri.org/IUserManagement/CreateExternalGroupResponse")]
        UserManagement.Group CreateExternalGroup(UserManagement.AuthenticationInfo auth, string groupName, string externalProvider, string externalId, System.Guid[] memberIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/AddMembersToInternalGroup", ReplyAction="http://tempuri.org/IUserManagement/AddMembersToInternalGroupResponse")]
        void AddMembersToInternalGroup(UserManagement.AuthenticationInfo auth, System.Guid groupId, System.Guid[] memberIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/RemoveMembersFromInternalGroup", ReplyAction="http://tempuri.org/IUserManagement/RemoveMembersFromInternalGroupResponse")]
        void RemoveMembersFromInternalGroup(UserManagement.AuthenticationInfo auth, System.Guid groupId, System.Guid[] memberIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/AddMembersToExternalGroup", ReplyAction="http://tempuri.org/IUserManagement/AddMembersToExternalGroupResponse")]
        void AddMembersToExternalGroup(UserManagement.AuthenticationInfo auth, string externalProviderName, string externalGroupId, System.Guid[] memberIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/RemoveMembersFromExternalGroup", ReplyAction="http://tempuri.org/IUserManagement/RemoveMembersFromExternalGroupResponse")]
        void RemoveMembersFromExternalGroup(UserManagement.AuthenticationInfo auth, string externalProviderName, string externalGroupId, System.Guid[] memberIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/SyncExternalUser", ReplyAction="http://tempuri.org/IUserManagement/SyncExternalUserResponse")]
        void SyncExternalUser(UserManagement.AuthenticationInfo auth, string firstName, string lastName, string email, bool EmailSessionNotifications, string[] externalGroupIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/DeleteGroup", ReplyAction="http://tempuri.org/IUserManagement/DeleteGroupResponse")]
        void DeleteGroup(UserManagement.AuthenticationInfo auth, System.Guid groupId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/GetGroup", ReplyAction="http://tempuri.org/IUserManagement/GetGroupResponse")]
        UserManagement.Group GetGroup(UserManagement.AuthenticationInfo auth, System.Guid groupId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/ListGroups", ReplyAction="http://tempuri.org/IUserManagement/ListGroupsResponse")]
        UserManagement.ListGroupsResponse ListGroups(UserManagement.AuthenticationInfo auth, UserManagement.Pagination pagination);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/GetGroupsByName", ReplyAction="http://tempuri.org/IUserManagement/GetGroupsByNameResponse")]
        UserManagement.Group[] GetGroupsByName(UserManagement.AuthenticationInfo auth, string groupName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/GetUsersInGroup", ReplyAction="http://tempuri.org/IUserManagement/GetUsersInGroupResponse")]
        System.Guid[] GetUsersInGroup(UserManagement.AuthenticationInfo auth, System.Guid groupId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/SetUserHasLoggedIn", ReplyAction="http://tempuri.org/IUserManagement/SetUserHasLoggedInResponse")]
        void SetUserHasLoggedIn(UserManagement.AuthenticationInfo auth, System.Guid userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/GetUserMeetingsRecordingFolderIdForUser", ReplyAction="http://tempuri.org/IUserManagement/GetUserMeetingsRecordingFolderIdForUserRespons" +
            "e")]
        System.Nullable<System.Guid> GetUserMeetingsRecordingFolderIdForUser(UserManagement.AuthenticationInfo auth, string userKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/SetUserMeetingsRecordingFolderIdForUser", ReplyAction="http://tempuri.org/IUserManagement/SetUserMeetingsRecordingFolderIdForUserRespons" +
            "e")]
        void SetUserMeetingsRecordingFolderIdForUser(UserManagement.AuthenticationInfo auth, string userKey, System.Guid meetingsFolderId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IUserManagementChannel : UserManagement.IUserManagement, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class UserManagementClient : System.ServiceModel.ClientBase<UserManagement.IUserManagement>, UserManagement.IUserManagement
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public UserManagementClient(EndpointConfiguration endpointConfiguration) : 
                base(UserManagementClient.GetBindingForEndpoint(endpointConfiguration), UserManagementClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UserManagementClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(UserManagementClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UserManagementClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(UserManagementClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UserManagementClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Guid CreateUser(UserManagement.AuthenticationInfo auth, UserManagement.User user, string initialPassword)
        {
            return base.Channel.CreateUser(auth, user, initialPassword);
        }
        
        public UserManagement.User[] CreateUsers(UserManagement.AuthenticationInfo auth, UserManagement.User[] users)
        {
            return base.Channel.CreateUsers(auth, users);
        }
        
        public UserManagement.User GetUserByKey(UserManagement.AuthenticationInfo auth, string userKey)
        {
            return base.Channel.GetUserByKey(auth, userKey);
        }
        
        public UserManagement.User[] GetUsers(UserManagement.AuthenticationInfo auth, System.Guid[] userIds)
        {
            return base.Channel.GetUsers(auth, userIds);
        }
        
        public UserManagement.ListUsersResponse ListUsers(UserManagement.AuthenticationInfo auth, UserManagement.ListUsersRequest parameters, string searchQuery)
        {
            return base.Channel.ListUsers(auth, parameters, searchQuery);
        }
        
        public void UpdateContactInfo(UserManagement.AuthenticationInfo auth, System.Guid userId, string firstName, string lastName, string email, bool sendNotifications)
        {
            base.Channel.UpdateContactInfo(auth, userId, firstName, lastName, email, sendNotifications);
        }
        
        public void UpdateUserBio(UserManagement.AuthenticationInfo auth, System.Guid userId, string bio)
        {
            base.Channel.UpdateUserBio(auth, userId, bio);
        }
        
        public void UpdatePassword(UserManagement.AuthenticationInfo auth, System.Guid userId, string newPassword)
        {
            base.Channel.UpdatePassword(auth, userId, newPassword);
        }
        
        public void ResetPassword(UserManagement.AuthenticationInfo auth, System.Guid userId)
        {
            base.Channel.ResetPassword(auth, userId);
        }
        
        public void UnlockAccount(UserManagement.AuthenticationInfo auth, System.Guid userId)
        {
            base.Channel.UnlockAccount(auth, userId);
        }
        
        public void SetSystemRole(UserManagement.AuthenticationInfo auth, System.Guid userId, UserManagement.SystemRole role)
        {
            base.Channel.SetSystemRole(auth, userId, role);
        }
        
        public void DeleteUsers(UserManagement.AuthenticationInfo auth, System.Guid[] userIds)
        {
            base.Channel.DeleteUsers(auth, userIds);
        }
        
        public UserManagement.Group CreateInternalGroup(UserManagement.AuthenticationInfo auth, string groupName, System.Guid[] memberIds)
        {
            return base.Channel.CreateInternalGroup(auth, groupName, memberIds);
        }
        
        public bool GetGroupIsPublic(UserManagement.AuthenticationInfo auth, System.Guid groupId)
        {
            return base.Channel.GetGroupIsPublic(auth, groupId);
        }
        
        public void SetGroupIsPublic(UserManagement.AuthenticationInfo auth, System.Guid groupId, bool isPublic)
        {
            base.Channel.SetGroupIsPublic(auth, groupId, isPublic);
        }
        
        public UserManagement.Group CreateExternalGroup(UserManagement.AuthenticationInfo auth, string groupName, string externalProvider, string externalId, System.Guid[] memberIds)
        {
            return base.Channel.CreateExternalGroup(auth, groupName, externalProvider, externalId, memberIds);
        }
        
        public void AddMembersToInternalGroup(UserManagement.AuthenticationInfo auth, System.Guid groupId, System.Guid[] memberIds)
        {
            base.Channel.AddMembersToInternalGroup(auth, groupId, memberIds);
        }
        
        public void RemoveMembersFromInternalGroup(UserManagement.AuthenticationInfo auth, System.Guid groupId, System.Guid[] memberIds)
        {
            base.Channel.RemoveMembersFromInternalGroup(auth, groupId, memberIds);
        }
        
        public void AddMembersToExternalGroup(UserManagement.AuthenticationInfo auth, string externalProviderName, string externalGroupId, System.Guid[] memberIds)
        {
            base.Channel.AddMembersToExternalGroup(auth, externalProviderName, externalGroupId, memberIds);
        }
        
        public void RemoveMembersFromExternalGroup(UserManagement.AuthenticationInfo auth, string externalProviderName, string externalGroupId, System.Guid[] memberIds)
        {
            base.Channel.RemoveMembersFromExternalGroup(auth, externalProviderName, externalGroupId, memberIds);
        }
        
        public void SyncExternalUser(UserManagement.AuthenticationInfo auth, string firstName, string lastName, string email, bool EmailSessionNotifications, string[] externalGroupIds)
        {
            base.Channel.SyncExternalUser(auth, firstName, lastName, email, EmailSessionNotifications, externalGroupIds);
        }
        
        public void DeleteGroup(UserManagement.AuthenticationInfo auth, System.Guid groupId)
        {
            base.Channel.DeleteGroup(auth, groupId);
        }
        
        public UserManagement.Group GetGroup(UserManagement.AuthenticationInfo auth, System.Guid groupId)
        {
            return base.Channel.GetGroup(auth, groupId);
        }
        
        public UserManagement.ListGroupsResponse ListGroups(UserManagement.AuthenticationInfo auth, UserManagement.Pagination pagination)
        {
            return base.Channel.ListGroups(auth, pagination);
        }
        
        public UserManagement.Group[] GetGroupsByName(UserManagement.AuthenticationInfo auth, string groupName)
        {
            return base.Channel.GetGroupsByName(auth, groupName);
        }
        
        public System.Guid[] GetUsersInGroup(UserManagement.AuthenticationInfo auth, System.Guid groupId)
        {
            return base.Channel.GetUsersInGroup(auth, groupId);
        }
        
        public void SetUserHasLoggedIn(UserManagement.AuthenticationInfo auth, System.Guid userId)
        {
            base.Channel.SetUserHasLoggedIn(auth, userId);
        }
        
        public System.Nullable<System.Guid> GetUserMeetingsRecordingFolderIdForUser(UserManagement.AuthenticationInfo auth, string userKey)
        {
            return base.Channel.GetUserMeetingsRecordingFolderIdForUser(auth, userKey);
        }
        
        public void SetUserMeetingsRecordingFolderIdForUser(UserManagement.AuthenticationInfo auth, string userKey, System.Guid meetingsFolderId)
        {
            base.Channel.SetUserMeetingsRecordingFolderIdForUser(auth, userKey, meetingsFolderId);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IUserManagement))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IUserManagement1))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IUserManagement))
            {
                return new System.ServiceModel.EndpointAddress("https://leedstest.cloud.panopto.eu/Panopto/PublicAPI/4.2/UserManagement.svc");
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IUserManagement1))
            {
                return new System.ServiceModel.EndpointAddress("http://leedstest.cloud.panopto.eu/Panopto/PublicAPI/4.2/UserManagement.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IUserManagement,
            
            BasicHttpBinding_IUserManagement1,
        }
    }
}
